---
collections:
  - name: ansible.posix
    version: 2.2.0
  - name: infisical.vault
    version: 1.2.1
  - name: grafana.grafana
    version: 6.1.0
  - name: community.proxmox
    version: 1.6.0
  - name: oxlorg.opnsense
    version: 25.7.8
