pipeline {
    agent {
        kubernetes {
            defaultContainer 'jnlp'
            yamlFile 'ansible/jenkins-pod.yaml'
        }
    }
    stages {
        stage('Playbook') {
            steps {
                container('ansible') {
                    script {

                        def playbook = 'ansible/initial_setup/site.yml'
                        def inventory = 'ansible/initial_setup/inventory.ini'
                        ansiblePlaybook(
                            credentialsId: 'initial_setup_private_key',
                            inventory: inventory,
                            playbook: playbook,
                            hostKeyChecking: false,
                            colorized: true,
                            become: true,
                            extraVars: [
                                ansible_user_password: credentials('ansible_user').password,
                                ansible_user_public_ssh_key: credentials('ansible_user_public_ssh_key')
                            ]
                        )
                    }
                }
            }
        }
    }
}
