- name: Read versions.yaml
  ansible.builtin.slurp:
    src: "{{ playbook_dir }}/../terragrunt/{{ cluster }}/versions.yaml"
  register: talos_node_update_versions_file

- name: Get nodes from kubernetes cluster
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    kubeconfig: "/tmp/kube_config.yaml"
  register: talos_node_update_nodes

- name: Set fact for target talos version
  ansible.builtin.set_fact:
    talos_node_update_target_version: "{{ (talos_node_update_versions_file.content | b64decode | from_yaml).talos }}"

## Gets all nodes that aren't on the correct version and orders them with control plane nodes first.
- name: Set fact for nodes requiring talos update
  ansible.builtin.set_fact:
    talos_node_update_nodes_to_update: >-
      {{
        (
          talos_node_update_nodes.resources
          | selectattr('status.nodeInfo.osImage', 'defined')
          | rejectattr('status.nodeInfo.osImage', 'search', talos_node_update_target_version)
          | selectattr('metadata.labels', 'defined')
          | selectattr('metadata.labels["node-role.kubernetes.io/control-plane"]', 'defined')
          | list
        ) + (
          talos_node_update_nodes.resources
          | selectattr('status.nodeInfo.osImage', 'defined')
          | rejectattr('status.nodeInfo.osImage', 'search', talos_node_update_target_version)
          | rejectattr('metadata.labels["node-role.kubernetes.io/control-plane"]', 'defined')
          | list
        )
      }}

- name: Update Talos node
  ansible.builtin.command: >-
    talosctl --talosconfig /tmp/talos_config.yaml upgrade --wait \
    -n {{ item.status.addresses | selectattr('type', 'equalto', 'InternalIP') | map(attribute='address') | list | first }} \
    --image factory.talos.dev/metal-installer/{{ item.metadata.annotations['extensions.talos.dev/schematic'] }}:{{ talos_node_update_target_version }}
  changed_when: true
  loop: "{{ talos_node_update_nodes_to_update }}"
  loop_control:
    label: "{{ item.metadata.name }}"
