name: Kubernetes Tests

# Run manually and have option for branch
on:
  workflow_dispatch:
    inputs:
      teardown:
        description: 'Whether to teardown the cluster after tests (true/false)'
        required: false
        default: 'true'
jobs:
  test-kubernetes:
    runs-on: self-hosted
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: tests/kubernetes/go.mod
          cache: true

      - name: Run Kubernetes tests
        run: |
          cd tests
          if [ "${{ github.event.inputs.teardown }}" = "false" ]; then
            make test-kubernetes-no-teardown
          else
            make test-kubernetes
          fi

      - name: Generate test report
        if: always()
        run: |
          cd tests
          make report-kubernetes

      - name: Test Summary
        uses: test-summary/action@v2
        with:
            paths: "tests/kubernetes/test_output/report.xml"
        if: always()