name: Kubernetes Tests

# Run manually and have option for branch
on:
  workflow_dispatch:
    inputs:
      teardown:
        description: Teardown the cluster after tests
        type: boolean
        required: false
        default: true

# Prevent concurrent runs of this workflow to avoid conflicts, but allow concurrent runs of other workflows
concurrency:
  group: 'test-terragrunt-main'

env:
  INFISICAL_HOST: "https://secrets.homelab.example"
  INFISICAL_UNIVERSAL_AUTH_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
  INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}

  AWS_ENDPOINT_URL_S3: "https://s3.eu-central-003.backblazeb2.com"
  AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY_SECRET }}
  TG_PROVIDER_CACHE: 1

jobs:
  test-kubernetes:
    runs-on: self-hosted
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: tests/kubernetes/go.mod
          cache: true

      - name: Run Kubernetes tests
        run: |
          cd tests
          if [ "${{ inputs.teardown }}" = "false" ]; then
            make test-kubernetes-no-teardown
          else
            make test-kubernetes
          fi

      - name: Generate test report
        if: always()
        run: |
          cd tests
          make report-kubernetes

      - name: Test Summary
        uses: test-summary/action@v2
        with:
            paths: "tests/kubernetes/test_output/report.xml"
        if: always()